name: Test Branch

on:
  push:
    branches:
      - main
      - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      dind:
        image: docker:23.0-rc-dind-rootless
        ports:
          - 2375:2375
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4

      - uses: golangci/golangci-lint-action@v3

      - name: Run tests
        run: |
          go test -v -covermode=atomic -coverprofile=coverage.out -race ./...
          go tool cover -func="coverage.out"

      - uses: coverallsapp/github-action@v2
        with:
          file: coverage.out
